import {
  ADMIN_DISPUTE_REPORTS_ROUTE,
  ADMIN_MESSAGES_ROUTE,
  ADMIN_NOTIFICATIONS_ROUTE,
  ADMIN_PAYOUT_QUEUE_ROUTE,
  ADMIN_SCHEDULES_ROUTE,
  ADMIN_TUTOR_APPLICATIONS_ROUTE,
  ADMIN_TUTORS_ROUTE,
  PARENT_MESSAGES_ROUTE,
  PARENT_NOTIFICATIONS_ROUTE,
  PARENT_SCHEDULE_ROUTE,
  PARENT_SETTINGS_ROUTE,
  PARENT_STUDENTS_ROUTE,
  STUDENT_MESSAGES_ROUTE,
  STUDENT_NOTIFICATIONS_ROUTE,
  STUDENT_SCHEDULE_ROUTE,
  STUDENT_SETTINGS_ROUTE,
  TUTOR_AVAILABILITY_ROUTE,
  TUTOR_EARNINGS_ROUTE,
  TUTOR_MESSAGES_ROUTE,
  TUTOR_NOTIFICATIONS_ROUTE,
  TUTOR_SCHEDULE_ROUTE,
} from "@/lib/routes";

export type NotificationRole = "admin" | "student" | "tutor" | "parent";

export type NotificationActionType = "review" | "investigate" | "view" | "none";

export type NotificationItem = {
  id: string;
  title: string;
  message: string;
  timeLabel: string;
  category: string;
  unread: boolean;
  section: "new" | "earlier";
  action: NotificationActionType;
  href?: string;
};

export const notificationsByRole: Record<NotificationRole, NotificationItem[]> = {
  admin: [
    {
      id: "admin-1",
      title: "New tutor application",
      message: "James Miller applied to join as a Physics & Calculus tutor. Background check pending.",
      timeLabel: "2 hours ago",
      category: "Tutor Applications",
      unread: true,
      section: "new",
      action: "review",
      href: ADMIN_TUTOR_APPLICATIONS_ROUTE,
    },
    {
      id: "admin-2",
      title: "Dispute reported",
      message: "Patricia Johnson reported a cancellation dispute for session #SS-2039.",
      timeLabel: "Yesterday · 6:30 PM",
      category: "Session Alerts",
      unread: true,
      section: "new",
      action: "investigate",
      href: ADMIN_DISPUTE_REPORTS_ROUTE,
    },
    {
      id: "admin-3",
      title: "Payout processed",
      message: "Weekly payout of $540.00 was sent to Marcus Reynolds successfully.",
      timeLabel: "Mar 19 · 9:00 AM",
      category: "Payments",
      unread: true,
      section: "earlier",
      action: "view",
      href: ADMIN_PAYOUT_QUEUE_ROUTE,
    },
    {
      id: "admin-4",
      title: "Tutor application approved",
      message: "David Kim's tutor application was approved and is now active.",
      timeLabel: "Mar 18 · 3:15 PM",
      category: "Tutor Applications",
      unread: true,
      section: "earlier",
      action: "view",
      href: `${ADMIN_TUTORS_ROUTE}/TU-2003`,
    },
    {
      id: "admin-5",
      title: "System maintenance scheduled",
      message: "Platform maintenance is scheduled for Sunday, March 22 from 2:00 AM to 4:00 AM EST.",
      timeLabel: "Mar 17 · 11:00 AM",
      category: "System",
      unread: true,
      section: "earlier",
      action: "none",
    },
    {
      id: "admin-6",
      title: "Session dashboard updated",
      message: "The schedules dashboard now reflects all completed and pending sessions in real time.",
      timeLabel: "Mar 15 · 2:00 PM",
      category: "System",
      unread: false,
      section: "earlier",
      action: "view",
      href: ADMIN_SCHEDULES_ROUTE,
    },
  ],
  student: [
    {
      id: "student-1",
      title: "Upcoming session reminder",
      message: "Your Algebra II session with Marcus Reynolds starts in 2 hours.",
      timeLabel: "Today · 9:00 AM",
      category: "Sessions",
      unread: true,
      section: "new",
      action: "view",
      href: STUDENT_SCHEDULE_ROUTE,
    },
    {
      id: "student-2",
      title: "New message from tutor",
      message: "Marcus Reynolds replied to your reschedule request.",
      timeLabel: "Today · 8:15 AM",
      category: "Messages",
      unread: true,
      section: "new",
      action: "view",
      href: STUDENT_MESSAGES_ROUTE,
    },
    {
      id: "student-3",
      title: "Payment received",
      message: "Your payment for the next session was successfully processed.",
      timeLabel: "Yesterday · 5:20 PM",
      category: "Payments",
      unread: true,
      section: "earlier",
      action: "view",
      href: STUDENT_SCHEDULE_ROUTE,
    },
    {
      id: "student-4",
      title: "Profile reminder",
      message: "Update your profile information so tutors can contact you faster.",
      timeLabel: "Mar 19 · 1:45 PM",
      category: "System",
      unread: false,
      section: "earlier",
      action: "view",
      href: STUDENT_SETTINGS_ROUTE,
    },
  ],
  tutor: [
    {
      id: "tutor-1",
      title: "New session booked",
      message: "A new Reading session with Maya Wilson was booked for Thursday.",
      timeLabel: "Today · 10:00 AM",
      category: "Sessions",
      unread: true,
      section: "new",
      action: "view",
      href: TUTOR_SCHEDULE_ROUTE,
    },
    {
      id: "tutor-2",
      title: "New message from student",
      message: "Jordan Wilson replied to your reschedule message.",
      timeLabel: "Today · 9:40 AM",
      category: "Messages",
      unread: true,
      section: "new",
      action: "view",
      href: TUTOR_MESSAGES_ROUTE,
    },
    {
      id: "tutor-3",
      title: "Weekly payout ready",
      message: "Your payout for completed sessions this week is ready to review.",
      timeLabel: "Yesterday · 4:05 PM",
      category: "Payments",
      unread: true,
      section: "earlier",
      action: "view",
      href: TUTOR_EARNINGS_ROUTE,
    },
    {
      id: "tutor-4",
      title: "Availability update",
      message: "Your availability calendar has pending slots that can be published.",
      timeLabel: "Mar 18 · 11:20 AM",
      category: "System",
      unread: false,
      section: "earlier",
      action: "view",
      href: TUTOR_AVAILABILITY_ROUTE,
    },
  ],
  parent: [
    {
      id: "parent-1",
      title: "Session reminder",
      message: "Sophie L's next tutoring session starts in 2 hours.",
      timeLabel: "Today · 8:45 AM",
      category: "Sessions",
      unread: true,
      section: "new",
      action: "view",
      href: PARENT_SCHEDULE_ROUTE,
    },
    {
      id: "parent-2",
      title: "Message from tutor",
      message: "Priya Patel replied with homework feedback for Sophie L.",
      timeLabel: "Today · 8:10 AM",
      category: "Messages",
      unread: true,
      section: "new",
      action: "view",
      href: PARENT_MESSAGES_ROUTE,
    },
    {
      id: "parent-3",
      title: "Billing update",
      message: "Your latest session charge was processed successfully.",
      timeLabel: "Yesterday · 6:30 PM",
      category: "Payments",
      unread: true,
      section: "earlier",
      action: "view",
      href: PARENT_STUDENTS_ROUTE,
    },
    {
      id: "parent-4",
      title: "Notification settings",
      message: "Review your notification preferences to control how you receive updates.",
      timeLabel: "Mar 19 · 2:15 PM",
      category: "System",
      unread: false,
      section: "earlier",
      action: "view",
      href: PARENT_SETTINGS_ROUTE,
    },
  ],
};

export function getNotificationsForRole(role: NotificationRole) {
  return notificationsByRole[role] ?? [];
}
