export type StudentScheduleItem = {
  id: string;
  tutorId: string;
  tutorInitials: string;
  tutorName: string;
  subject: string;
  date: string;
  time: string;
  duration: string;
  type: "Virtual" | "In-Person";
  status: "Upcoming" | "Completed" | "Cancelled";
};

export const studentScheduleItems: StudentScheduleItem[] = [
  {
    id: "s1",
    tutorId: "101",
    tutorInitials: "MT",
    tutorName: "Marcus Thompson",
    subject: "Algebra II",
    date: "Mon, Mar 30",
    time: "4:00 PM",
    duration: "60 min",
    type: "Virtual",
    status: "Upcoming",
  },
  {
    id: "s2",
    tutorId: "102",
    tutorInitials: "SA",
    tutorName: "Sandra Avery",
    subject: "English Literature",
    date: "Wed, Apr 1",
    time: "3:30 PM",
    duration: "45 min",
    type: "In-Person",
    status: "Upcoming",
  },
  {
    id: "s3",
    tutorId: "103",
    tutorInitials: "RJ",
    tutorName: "Rebecca Jones",
    subject: "Biology",
    date: "Fri, Apr 3",
    time: "5:00 PM",
    duration: "60 min",
    type: "Virtual",
    status: "Upcoming",
  },
  {
    id: "s4",
    tutorId: "104",
    tutorInitials: "DL",
    tutorName: "Derek Lewis",
    subject: "ACT/SAT Prep",
    date: "Mon, Mar 23",
    time: "6:00 PM",
    duration: "60 min",
    type: "Virtual",
    status: "Completed",
  },
  {
    id: "s5",
    tutorId: "105",
    tutorInitials: "KW",
    tutorName: "Karen Wright",
    subject: "Reading",
    date: "Wed, Mar 18",
    time: "4:00 PM",
    duration: "45 min",
    type: "In-Person",
    status: "Completed",
  },
  {
    id: "s6",
    tutorId: "106",
    tutorInitials: "JM",
    tutorName: "James Morgan",
    subject: "U.S. History",
    date: "Tue, Mar 10",
    time: "5:30 PM",
    duration: "60 min",
    type: "Virtual",
    status: "Completed",
  },
  {
    id: "s7",
    tutorId: "101",
    tutorInitials: "MT",
    tutorName: "Marcus Thompson",
    subject: "Geometry",
    date: "Thu, Mar 12",
    time: "4:30 PM",
    duration: "45 min",
    type: "Virtual",
    status: "Completed",
  },
  {
    id: "s8",
    tutorId: "102",
    tutorInitials: "SA",
    tutorName: "Sandra Avery",
    subject: "Essay Writing",
    date: "Fri, Mar 6",
    time: "3:00 PM",
    duration: "45 min",
    type: "In-Person",
    status: "Completed",
  },
  {
    id: "s9",
    tutorId: "103",
    tutorInitials: "RJ",
    tutorName: "Rebecca Jones",
    subject: "Chemistry",
    date: "Mon, Feb 24",
    time: "5:00 PM",
    duration: "60 min",
    type: "Virtual",
    status: "Completed",
  },
  {
    id: "s10",
    tutorId: "104",
    tutorInitials: "DL",
    tutorName: "Derek Lewis",
    subject: "Statistics",
    date: "Tue, Mar 17",
    time: "6:30 PM",
    duration: "60 min",
    type: "Virtual",
    status: "Completed",
  },
  {
    id: "s11",
    tutorId: "105",
    tutorInitials: "KW",
    tutorName: "Karen Wright",
    subject: "Phonics",
    date: "Thu, Feb 20",
    time: "3:30 PM",
    duration: "45 min",
    type: "In-Person",
    status: "Completed",
  },
  {
    id: "s12",
    tutorId: "101",
    tutorInitials: "MT",
    tutorName: "Marcus Thompson",
    subject: "Algebra I",
    date: "Tue, Feb 11",
    time: "4:00 PM",
    duration: "60 min",
    type: "Virtual",
    status: "Completed",
  },
  {
    id: "s13",
    tutorId: "102",
    tutorInitials: "SA",
    tutorName: "Sandra Avery",
    subject: "Writing",
    date: "Mon, Jan 27",
    time: "3:30 PM",
    duration: "45 min",
    type: "In-Person",
    status: "Completed",
  },
  {
    id: "s14",
    tutorId: "103",
    tutorInitials: "RJ",
    tutorName: "Rebecca Jones",
    subject: "Biology",
    date: "Wed, Jan 15",
    time: "5:00 PM",
    duration: "60 min",
    type: "Virtual",
    status: "Completed",
  },
  {
    id: "s15",
    tutorId: "104",
    tutorInitials: "DL",
    tutorName: "Derek Lewis",
    subject: "Math",
    date: "Thu, Jan 9",
    time: "7:00 PM",
    duration: "60 min",
    type: "Virtual",
    status: "Completed",
  },
  {
    id: "s16",
    tutorId: "105",
    tutorInitials: "KW",
    tutorName: "Karen Wright",
    subject: "Literacy",
    date: "Fri, Jan 3",
    time: "4:15 PM",
    duration: "45 min",
    type: "In-Person",
    status: "Completed",
  },
  {
    id: "s17",
    tutorId: "106",
    tutorInitials: "JM",
    tutorName: "James Morgan",
    subject: "AP History",
    date: "Wed, Mar 11",
    time: "1:00 PM",
    duration: "60 min",
    type: "Virtual",
    status: "Completed",
  },
  {
    id: "s18",
    tutorId: "101",
    tutorInitials: "MT",
    tutorName: "Marcus Thompson",
    subject: "Algebra II",
    date: "Fri, Mar 13",
    time: "4:00 PM",
    duration: "60 min",
    type: "Virtual",
    status: "Completed",
  },
  {
    id: "s19",
    tutorId: "102",
    tutorInitials: "SA",
    tutorName: "Sandra Avery",
    subject: "English",
    date: "Tue, Mar 24",
    time: "5:15 PM",
    duration: "45 min",
    type: "In-Person",
    status: "Cancelled",
  },
  {
    id: "s20",
    tutorId: "103",
    tutorInitials: "RJ",
    tutorName: "Rebecca Jones",
    subject: "Earth Science",
    date: "Thu, Mar 26",
    time: "4:45 PM",
    duration: "60 min",
    type: "Virtual",
    status: "Cancelled",
  },
];
